### ISSUE TITLE
Any better way to check if the permission is given?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-AppUsageStatistics#1]
I've tried to check the permission, but I've failed (posted about it here: http://stackoverflow.com/q/28921136/878126 ) . 

It's just that checking that the list/map is empty assumes that the result being empty mean that the permission isn't granted...

**Comment by keyboardsurfer** [comment]
Could not reproduce the issue with this sample.

**Comment by AndroidDeveloperLB** [comment]
cannot reproduce what? having an empty result ? just set the time range to be as small as possible.

**Comment by keyboardsurfer** [comment]
I could not reproduce the issue you described can within this sample application.
If your post is not regarding this sample, stackoverflow is the correct forum for this.

**Comment by AndroidDeveloperLB** [comment]
Logically, it doesn't make sense to use it this way. If it was possible to reset the usage stats, for example, your solution won't work. Same goes for the special case that your app is the very first one to launch (even before the launcher) on the very first boot of the device.

I think this solution might be better:
http://stackoverflow.com/a/28921586/878126
