### ISSUE TITLE
AAPT2 error: check logs for details

### ISSUE THREAD

**Issue by antoniosap** [googlesamples/android-AppUsageStatistics#8]
error: resource android:attr/ttcIndex not found.
Message{kind=ERROR, text=error: resource android:attr/ttcIndex not found., sources=[/home/antonio/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/d1af2b597c9654ca5bef82f77d9f7133/res/values/values.xml:251:5-69], original message=, tool name=Optional.of(AAPT)}

and many similar
any ideas?

**Comment by Gabriel0402** [comment]
Change the dependencies version:
dependencies {
    implementation "com.android.support:support-v4:27.1.1"
    implementation "com.android.support:support-v13:27.1.1"
    implementation "com.android.support:cardview-v7:27.1.1"
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation 'com.android.support:recyclerview-v7:27.1.1'
}

**Comment by rbvm** [comment]
Didn't worked for me.

**Comment by J370** [comment]
> 
> 
> Didn't worked for me.

Seems to be working as of now.
